//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevTools.Plugin.DBTool.Oracle.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevTools.Plugin.DBTool.Oracle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SELECT
        ///    NAME
        ///FROM
        ///    V$DATABASE
        ///ORDER BY
        ///    NAME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_GetDatabaseName {
            get {
                return ResourceManager.GetString("SQL_GetDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- 0：表名
        ///SELECT
        ///    ATCOL.COLUMN_ID     AS &quot;ID&quot;
        ///    , ATCOL.COLUMN_NAME AS &quot;Name&quot;
        ///    , ATCOL.DATA_TYPE   AS &quot;SystemType&quot;
        ///    , ATCOL.DATA_LENGTH AS &quot;Length&quot;
        ///FROM
        ///    ALL_TAB_COLUMNS ATCOL
        ///WHERE
        ///    ATCOL.TABLE_NAME = &apos;{0}&apos;
        ///ORDER BY
        ///    ATCOL.COLUMN_ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_GetTableColumns {
            get {
                return ResourceManager.GetString("SQL_GetTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- 0：表名
        ///SELECT
        ///    ROWNUM              AS &quot;IndexId&quot;
        ///    , AIDX.INDEX_NAME   AS &quot;IndexName&quot;
        ///    , AICOL.COLUMN_NAME AS &quot;ColumnName&quot;
        ///    , CASE AICOL.DESCEND
        ///      WHEN &apos;Y&apos; THEN &apos;DESC&apos;
        ///      WHEN &apos;N&apos; THEN &apos;ASC&apos;
        ///      ELSE &apos;ASC&apos; END    AS &quot;Sort&quot;
        ///    , CASE 
        ///      WHEN ACON.CONSTRAINT_TYPE = &apos;P&apos; AND AIDX.UNIQUENESS = &apos;UNIQUE&apos; THEN &apos;PK&apos;
        ///      ELSE &apos;&apos; END       AS &quot;PrimaryKey&quot;
        ///    , CASE AIDX.STATUS
        ///      WHEN &apos;UNUSABLE&apos; THEN &apos;TRUE&apos;
        ///      WHEN &apos;VALID&apos; THEN &apos;FALSE&apos;
        ///      ELSE &apos;FALSE&apos; END  AS &quot;Disabl [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_GetTableIndex {
            get {
                return ResourceManager.GetString("SQL_GetTableIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT
        ///    TABLE_NAME
        ///FROM
        ///    ALL_TABLES
        ///WHERE
        ///    TABLESPACE_NAME IS NOT NULL
        ///    AND TABLESPACE_NAME &lt;&gt; &apos;SYSTEM&apos;
        ///    AND TABLESPACE_NAME &lt;&gt; &apos;SYSAUX&apos;
        ///ORDER BY
        ///    TABLE_NAME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_GetTableName {
            get {
                return ResourceManager.GetString("SQL_GetTableName", resourceCulture);
            }
        }
    }
}
